// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mxnet.proto

/*
	Package mxnet is a generated protocol buffer package.

	It is generated from these files:
		mxnet.proto

	It has these top-level messages:
		Graph
*/
package mxnet

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import strings "strings"
import reflect "reflect"
import github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Graph struct {
	Nodes      []*Graph_Node      `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty" yaml:"nodes,omitempty"`
	ArgNodes   []int64            `protobuf:"varint,2,rep,packed,name=arg_nodes,json=argNodes" json:"arg_nodes,omitempty" yaml:"arg_nodes,omitempty"`
	NodeRowPtr []int64            `protobuf:"varint,3,rep,packed,name=node_row_ptr,json=nodeRowPtr" json:"node_row_ptr,omitempty" yaml:"node_row_ptr,omitempty"`
	Heads      []*Graph_NodeEntry `protobuf:"bytes,4,rep,name=heads" json:"heads,omitempty" yaml:"heads,omitempty"`
	Attrs      *Graph_Attributes  `protobuf:"bytes,5,opt,name=attrs" json:"attrs,omitempty" yaml:"attrs,omitempty"`
}

func (m *Graph) Reset()                    { *m = Graph{} }
func (*Graph) ProtoMessage()               {}
func (*Graph) Descriptor() ([]byte, []int) { return fileDescriptorMxnet, []int{0} }

func (m *Graph) GetNodes() []*Graph_Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Graph) GetArgNodes() []int64 {
	if m != nil {
		return m.ArgNodes
	}
	return nil
}

func (m *Graph) GetNodeRowPtr() []int64 {
	if m != nil {
		return m.NodeRowPtr
	}
	return nil
}

func (m *Graph) GetHeads() []*Graph_NodeEntry {
	if m != nil {
		return m.Heads
	}
	return nil
}

func (m *Graph) GetAttrs() *Graph_Attributes {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type Graph_NodeEntry struct {
	NodeId  int64 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty" yaml:"node_id,omitempty"`
	Index   int64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty" yaml:"input,omitempty"`
	Version int64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty" yaml:"version,omitempty"`
}

func (m *Graph_NodeEntry) Reset()                    { *m = Graph_NodeEntry{} }
func (*Graph_NodeEntry) ProtoMessage()               {}
func (*Graph_NodeEntry) Descriptor() ([]byte, []int) { return fileDescriptorMxnet, []int{0, 0} }

func (m *Graph_NodeEntry) GetNodeId() int64 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *Graph_NodeEntry) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Graph_NodeEntry) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type Graph_Node struct {
	Op               string             `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty" yaml:"op,omitempty"`
	Param            map[string]string  `protobuf:"bytes,2,rep,name=param" json:"param,omitempty" yaml:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Name             string             `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" yaml:"name,omitempty"`
	Inputs           []*Graph_NodeEntry `protobuf:"bytes,4,rep,name=inputs" json:"inputs,omitempty" yaml:"inputs,omitempty"`
	BackwardSourceId int64              `protobuf:"varint,5,opt,name=backward_source_id,json=backwardSourceId,proto3" json:"backward_source_id,omitempty" yaml:"backward_source_id,omitempty"`
	ControlDeps      []int64            `protobuf:"varint,6,rep,packed,name=control_deps,json=controlDeps" json:"control_deps,omitempty" yaml:"control_deps,omitempty"`
}

func (m *Graph_Node) Reset()                    { *m = Graph_Node{} }
func (*Graph_Node) ProtoMessage()               {}
func (*Graph_Node) Descriptor() ([]byte, []int) { return fileDescriptorMxnet, []int{0, 1} }

func (m *Graph_Node) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *Graph_Node) GetParam() map[string]string {
	if m != nil {
		return m.Param
	}
	return nil
}

func (m *Graph_Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Graph_Node) GetInputs() []*Graph_NodeEntry {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Graph_Node) GetBackwardSourceId() int64 {
	if m != nil {
		return m.BackwardSourceId
	}
	return 0
}

func (m *Graph_Node) GetControlDeps() []int64 {
	if m != nil {
		return m.ControlDeps
	}
	return nil
}

type Graph_Attributes struct {
	Attrs map[string]string `protobuf:"bytes,1,rep,name=attrs" json:"attrs,omitempty" yaml:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *Graph_Attributes) Reset()                    { *m = Graph_Attributes{} }
func (*Graph_Attributes) ProtoMessage()               {}
func (*Graph_Attributes) Descriptor() ([]byte, []int) { return fileDescriptorMxnet, []int{0, 2} }

func (m *Graph_Attributes) GetAttrs() map[string]string {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func init() {
	proto.RegisterType((*Graph)(nil), "carml.org.dlframework.frameworks.mxnet.Graph")
	proto.RegisterType((*Graph_NodeEntry)(nil), "carml.org.dlframework.frameworks.mxnet.Graph.NodeEntry")
	proto.RegisterType((*Graph_Node)(nil), "carml.org.dlframework.frameworks.mxnet.Graph.Node")
	proto.RegisterType((*Graph_Attributes)(nil), "carml.org.dlframework.frameworks.mxnet.Graph.Attributes")
}
func (this *Graph) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*Graph)
	if !ok {
		that2, ok := that.(Graph)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *Graph")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *Graph but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *Graph but is not nil && this == nil")
	}
	if len(this.Nodes) != len(that1.Nodes) {
		return fmt.Errorf("Nodes this(%v) Not Equal that(%v)", len(this.Nodes), len(that1.Nodes))
	}
	for i := range this.Nodes {
		if !this.Nodes[i].Equal(that1.Nodes[i]) {
			return fmt.Errorf("Nodes this[%v](%v) Not Equal that[%v](%v)", i, this.Nodes[i], i, that1.Nodes[i])
		}
	}
	if len(this.ArgNodes) != len(that1.ArgNodes) {
		return fmt.Errorf("ArgNodes this(%v) Not Equal that(%v)", len(this.ArgNodes), len(that1.ArgNodes))
	}
	for i := range this.ArgNodes {
		if this.ArgNodes[i] != that1.ArgNodes[i] {
			return fmt.Errorf("ArgNodes this[%v](%v) Not Equal that[%v](%v)", i, this.ArgNodes[i], i, that1.ArgNodes[i])
		}
	}
	if len(this.NodeRowPtr) != len(that1.NodeRowPtr) {
		return fmt.Errorf("NodeRowPtr this(%v) Not Equal that(%v)", len(this.NodeRowPtr), len(that1.NodeRowPtr))
	}
	for i := range this.NodeRowPtr {
		if this.NodeRowPtr[i] != that1.NodeRowPtr[i] {
			return fmt.Errorf("NodeRowPtr this[%v](%v) Not Equal that[%v](%v)", i, this.NodeRowPtr[i], i, that1.NodeRowPtr[i])
		}
	}
	if len(this.Heads) != len(that1.Heads) {
		return fmt.Errorf("Heads this(%v) Not Equal that(%v)", len(this.Heads), len(that1.Heads))
	}
	for i := range this.Heads {
		if !this.Heads[i].Equal(that1.Heads[i]) {
			return fmt.Errorf("Heads this[%v](%v) Not Equal that[%v](%v)", i, this.Heads[i], i, that1.Heads[i])
		}
	}
	if !this.Attrs.Equal(that1.Attrs) {
		return fmt.Errorf("Attrs this(%v) Not Equal that(%v)", this.Attrs, that1.Attrs)
	}
	return nil
}
func (this *Graph) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Graph)
	if !ok {
		that2, ok := that.(Graph)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if len(this.Nodes) != len(that1.Nodes) {
		return false
	}
	for i := range this.Nodes {
		if !this.Nodes[i].Equal(that1.Nodes[i]) {
			return false
		}
	}
	if len(this.ArgNodes) != len(that1.ArgNodes) {
		return false
	}
	for i := range this.ArgNodes {
		if this.ArgNodes[i] != that1.ArgNodes[i] {
			return false
		}
	}
	if len(this.NodeRowPtr) != len(that1.NodeRowPtr) {
		return false
	}
	for i := range this.NodeRowPtr {
		if this.NodeRowPtr[i] != that1.NodeRowPtr[i] {
			return false
		}
	}
	if len(this.Heads) != len(that1.Heads) {
		return false
	}
	for i := range this.Heads {
		if !this.Heads[i].Equal(that1.Heads[i]) {
			return false
		}
	}
	if !this.Attrs.Equal(that1.Attrs) {
		return false
	}
	return true
}
func (this *Graph_NodeEntry) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*Graph_NodeEntry)
	if !ok {
		that2, ok := that.(Graph_NodeEntry)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *Graph_NodeEntry")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *Graph_NodeEntry but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *Graph_NodeEntry but is not nil && this == nil")
	}
	if this.NodeId != that1.NodeId {
		return fmt.Errorf("NodeId this(%v) Not Equal that(%v)", this.NodeId, that1.NodeId)
	}
	if this.Index != that1.Index {
		return fmt.Errorf("Index this(%v) Not Equal that(%v)", this.Index, that1.Index)
	}
	if this.Version != that1.Version {
		return fmt.Errorf("Version this(%v) Not Equal that(%v)", this.Version, that1.Version)
	}
	return nil
}
func (this *Graph_NodeEntry) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Graph_NodeEntry)
	if !ok {
		that2, ok := that.(Graph_NodeEntry)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.NodeId != that1.NodeId {
		return false
	}
	if this.Index != that1.Index {
		return false
	}
	if this.Version != that1.Version {
		return false
	}
	return true
}
func (this *Graph_Node) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*Graph_Node)
	if !ok {
		that2, ok := that.(Graph_Node)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *Graph_Node")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *Graph_Node but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *Graph_Node but is not nil && this == nil")
	}
	if this.Op != that1.Op {
		return fmt.Errorf("Op this(%v) Not Equal that(%v)", this.Op, that1.Op)
	}
	if len(this.Param) != len(that1.Param) {
		return fmt.Errorf("Param this(%v) Not Equal that(%v)", len(this.Param), len(that1.Param))
	}
	for i := range this.Param {
		if this.Param[i] != that1.Param[i] {
			return fmt.Errorf("Param this[%v](%v) Not Equal that[%v](%v)", i, this.Param[i], i, that1.Param[i])
		}
	}
	if this.Name != that1.Name {
		return fmt.Errorf("Name this(%v) Not Equal that(%v)", this.Name, that1.Name)
	}
	if len(this.Inputs) != len(that1.Inputs) {
		return fmt.Errorf("Inputs this(%v) Not Equal that(%v)", len(this.Inputs), len(that1.Inputs))
	}
	for i := range this.Inputs {
		if !this.Inputs[i].Equal(that1.Inputs[i]) {
			return fmt.Errorf("Inputs this[%v](%v) Not Equal that[%v](%v)", i, this.Inputs[i], i, that1.Inputs[i])
		}
	}
	if this.BackwardSourceId != that1.BackwardSourceId {
		return fmt.Errorf("BackwardSourceId this(%v) Not Equal that(%v)", this.BackwardSourceId, that1.BackwardSourceId)
	}
	if len(this.ControlDeps) != len(that1.ControlDeps) {
		return fmt.Errorf("ControlDeps this(%v) Not Equal that(%v)", len(this.ControlDeps), len(that1.ControlDeps))
	}
	for i := range this.ControlDeps {
		if this.ControlDeps[i] != that1.ControlDeps[i] {
			return fmt.Errorf("ControlDeps this[%v](%v) Not Equal that[%v](%v)", i, this.ControlDeps[i], i, that1.ControlDeps[i])
		}
	}
	return nil
}
func (this *Graph_Node) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Graph_Node)
	if !ok {
		that2, ok := that.(Graph_Node)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Op != that1.Op {
		return false
	}
	if len(this.Param) != len(that1.Param) {
		return false
	}
	for i := range this.Param {
		if this.Param[i] != that1.Param[i] {
			return false
		}
	}
	if this.Name != that1.Name {
		return false
	}
	if len(this.Inputs) != len(that1.Inputs) {
		return false
	}
	for i := range this.Inputs {
		if !this.Inputs[i].Equal(that1.Inputs[i]) {
			return false
		}
	}
	if this.BackwardSourceId != that1.BackwardSourceId {
		return false
	}
	if len(this.ControlDeps) != len(that1.ControlDeps) {
		return false
	}
	for i := range this.ControlDeps {
		if this.ControlDeps[i] != that1.ControlDeps[i] {
			return false
		}
	}
	return true
}
func (this *Graph_Attributes) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*Graph_Attributes)
	if !ok {
		that2, ok := that.(Graph_Attributes)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *Graph_Attributes")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *Graph_Attributes but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *Graph_Attributes but is not nil && this == nil")
	}
	if len(this.Attrs) != len(that1.Attrs) {
		return fmt.Errorf("Attrs this(%v) Not Equal that(%v)", len(this.Attrs), len(that1.Attrs))
	}
	for i := range this.Attrs {
		if this.Attrs[i] != that1.Attrs[i] {
			return fmt.Errorf("Attrs this[%v](%v) Not Equal that[%v](%v)", i, this.Attrs[i], i, that1.Attrs[i])
		}
	}
	return nil
}
func (this *Graph_Attributes) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Graph_Attributes)
	if !ok {
		that2, ok := that.(Graph_Attributes)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if len(this.Attrs) != len(that1.Attrs) {
		return false
	}
	for i := range this.Attrs {
		if this.Attrs[i] != that1.Attrs[i] {
			return false
		}
	}
	return true
}
func (this *Graph) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&mxnet.Graph{")
	if this.Nodes != nil {
		s = append(s, "Nodes: "+fmt.Sprintf("%#v", this.Nodes)+",\n")
	}
	s = append(s, "ArgNodes: "+fmt.Sprintf("%#v", this.ArgNodes)+",\n")
	s = append(s, "NodeRowPtr: "+fmt.Sprintf("%#v", this.NodeRowPtr)+",\n")
	if this.Heads != nil {
		s = append(s, "Heads: "+fmt.Sprintf("%#v", this.Heads)+",\n")
	}
	if this.Attrs != nil {
		s = append(s, "Attrs: "+fmt.Sprintf("%#v", this.Attrs)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Graph_NodeEntry) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&mxnet.Graph_NodeEntry{")
	s = append(s, "NodeId: "+fmt.Sprintf("%#v", this.NodeId)+",\n")
	s = append(s, "Index: "+fmt.Sprintf("%#v", this.Index)+",\n")
	s = append(s, "Version: "+fmt.Sprintf("%#v", this.Version)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Graph_Node) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&mxnet.Graph_Node{")
	s = append(s, "Op: "+fmt.Sprintf("%#v", this.Op)+",\n")
	keysForParam := make([]string, 0, len(this.Param))
	for k, _ := range this.Param {
		keysForParam = append(keysForParam, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForParam)
	mapStringForParam := "map[string]string{"
	for _, k := range keysForParam {
		mapStringForParam += fmt.Sprintf("%#v: %#v,", k, this.Param[k])
	}
	mapStringForParam += "}"
	if this.Param != nil {
		s = append(s, "Param: "+mapStringForParam+",\n")
	}
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	if this.Inputs != nil {
		s = append(s, "Inputs: "+fmt.Sprintf("%#v", this.Inputs)+",\n")
	}
	s = append(s, "BackwardSourceId: "+fmt.Sprintf("%#v", this.BackwardSourceId)+",\n")
	s = append(s, "ControlDeps: "+fmt.Sprintf("%#v", this.ControlDeps)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Graph_Attributes) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&mxnet.Graph_Attributes{")
	keysForAttrs := make([]string, 0, len(this.Attrs))
	for k, _ := range this.Attrs {
		keysForAttrs = append(keysForAttrs, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForAttrs)
	mapStringForAttrs := "map[string]string{"
	for _, k := range keysForAttrs {
		mapStringForAttrs += fmt.Sprintf("%#v: %#v,", k, this.Attrs[k])
	}
	mapStringForAttrs += "}"
	if this.Attrs != nil {
		s = append(s, "Attrs: "+mapStringForAttrs+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringMxnet(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Graph) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Graph) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Nodes) > 0 {
		for _, msg := range m.Nodes {
			dAtA[i] = 0xa
			i++
			i = encodeVarintMxnet(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.ArgNodes) > 0 {
		dAtA2 := make([]byte, len(m.ArgNodes)*10)
		var j1 int
		for _, num1 := range m.ArgNodes {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		dAtA[i] = 0x12
		i++
		i = encodeVarintMxnet(dAtA, i, uint64(j1))
		i += copy(dAtA[i:], dAtA2[:j1])
	}
	if len(m.NodeRowPtr) > 0 {
		dAtA4 := make([]byte, len(m.NodeRowPtr)*10)
		var j3 int
		for _, num1 := range m.NodeRowPtr {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMxnet(dAtA, i, uint64(j3))
		i += copy(dAtA[i:], dAtA4[:j3])
	}
	if len(m.Heads) > 0 {
		for _, msg := range m.Heads {
			dAtA[i] = 0x22
			i++
			i = encodeVarintMxnet(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Attrs != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintMxnet(dAtA, i, uint64(m.Attrs.Size()))
		n5, err := m.Attrs.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	return i, nil
}

func (m *Graph_NodeEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Graph_NodeEntry) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.NodeId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintMxnet(dAtA, i, uint64(m.NodeId))
	}
	if m.Index != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMxnet(dAtA, i, uint64(m.Index))
	}
	if m.Version != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintMxnet(dAtA, i, uint64(m.Version))
	}
	return i, nil
}

func (m *Graph_Node) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Graph_Node) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Op) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMxnet(dAtA, i, uint64(len(m.Op)))
		i += copy(dAtA[i:], m.Op)
	}
	if len(m.Param) > 0 {
		for k, _ := range m.Param {
			dAtA[i] = 0x12
			i++
			v := m.Param[k]
			mapSize := 1 + len(k) + sovMxnet(uint64(len(k))) + 1 + len(v) + sovMxnet(uint64(len(v)))
			i = encodeVarintMxnet(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintMxnet(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintMxnet(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMxnet(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Inputs) > 0 {
		for _, msg := range m.Inputs {
			dAtA[i] = 0x22
			i++
			i = encodeVarintMxnet(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.BackwardSourceId != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintMxnet(dAtA, i, uint64(m.BackwardSourceId))
	}
	if len(m.ControlDeps) > 0 {
		dAtA7 := make([]byte, len(m.ControlDeps)*10)
		var j6 int
		for _, num1 := range m.ControlDeps {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA7[j6] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j6++
			}
			dAtA7[j6] = uint8(num)
			j6++
		}
		dAtA[i] = 0x32
		i++
		i = encodeVarintMxnet(dAtA, i, uint64(j6))
		i += copy(dAtA[i:], dAtA7[:j6])
	}
	return i, nil
}

func (m *Graph_Attributes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Graph_Attributes) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Attrs) > 0 {
		for k, _ := range m.Attrs {
			dAtA[i] = 0xa
			i++
			v := m.Attrs[k]
			mapSize := 1 + len(k) + sovMxnet(uint64(len(k))) + 1 + len(v) + sovMxnet(uint64(len(v)))
			i = encodeVarintMxnet(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintMxnet(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintMxnet(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	return i, nil
}

func encodeFixed64Mxnet(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Mxnet(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintMxnet(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func NewPopulatedGraph(r randyMxnet, easy bool) *Graph {
	this := &Graph{}
	if r.Intn(10) != 0 {
		v1 := r.Intn(5)
		this.Nodes = make([]*Graph_Node, v1)
		for i := 0; i < v1; i++ {
			this.Nodes[i] = NewPopulatedGraph_Node(r, easy)
		}
	}
	v2 := r.Intn(10)
	this.ArgNodes = make([]int64, v2)
	for i := 0; i < v2; i++ {
		this.ArgNodes[i] = int64(r.Int63())
		if r.Intn(2) == 0 {
			this.ArgNodes[i] *= -1
		}
	}
	v3 := r.Intn(10)
	this.NodeRowPtr = make([]int64, v3)
	for i := 0; i < v3; i++ {
		this.NodeRowPtr[i] = int64(r.Int63())
		if r.Intn(2) == 0 {
			this.NodeRowPtr[i] *= -1
		}
	}
	if r.Intn(10) != 0 {
		v4 := r.Intn(5)
		this.Heads = make([]*Graph_NodeEntry, v4)
		for i := 0; i < v4; i++ {
			this.Heads[i] = NewPopulatedGraph_NodeEntry(r, easy)
		}
	}
	if r.Intn(10) != 0 {
		this.Attrs = NewPopulatedGraph_Attributes(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGraph_NodeEntry(r randyMxnet, easy bool) *Graph_NodeEntry {
	this := &Graph_NodeEntry{}
	this.NodeId = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.NodeId *= -1
	}
	this.Index = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Index *= -1
	}
	this.Version = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Version *= -1
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGraph_Node(r randyMxnet, easy bool) *Graph_Node {
	this := &Graph_Node{}
	this.Op = string(randStringMxnet(r))
	if r.Intn(10) != 0 {
		v5 := r.Intn(10)
		this.Param = make(map[string]string)
		for i := 0; i < v5; i++ {
			this.Param[randStringMxnet(r)] = randStringMxnet(r)
		}
	}
	this.Name = string(randStringMxnet(r))
	if r.Intn(10) != 0 {
		v6 := r.Intn(5)
		this.Inputs = make([]*Graph_NodeEntry, v6)
		for i := 0; i < v6; i++ {
			this.Inputs[i] = NewPopulatedGraph_NodeEntry(r, easy)
		}
	}
	this.BackwardSourceId = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.BackwardSourceId *= -1
	}
	v7 := r.Intn(10)
	this.ControlDeps = make([]int64, v7)
	for i := 0; i < v7; i++ {
		this.ControlDeps[i] = int64(r.Int63())
		if r.Intn(2) == 0 {
			this.ControlDeps[i] *= -1
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGraph_Attributes(r randyMxnet, easy bool) *Graph_Attributes {
	this := &Graph_Attributes{}
	if r.Intn(10) != 0 {
		v8 := r.Intn(10)
		this.Attrs = make(map[string]string)
		for i := 0; i < v8; i++ {
			this.Attrs[randStringMxnet(r)] = randStringMxnet(r)
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyMxnet interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneMxnet(r randyMxnet) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringMxnet(r randyMxnet) string {
	v9 := r.Intn(100)
	tmps := make([]rune, v9)
	for i := 0; i < v9; i++ {
		tmps[i] = randUTF8RuneMxnet(r)
	}
	return string(tmps)
}
func randUnrecognizedMxnet(r randyMxnet, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldMxnet(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldMxnet(dAtA []byte, r randyMxnet, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateMxnet(dAtA, uint64(key))
		v10 := r.Int63()
		if r.Intn(2) == 0 {
			v10 *= -1
		}
		dAtA = encodeVarintPopulateMxnet(dAtA, uint64(v10))
	case 1:
		dAtA = encodeVarintPopulateMxnet(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateMxnet(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateMxnet(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateMxnet(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateMxnet(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Graph) Size() (n int) {
	var l int
	_ = l
	if len(m.Nodes) > 0 {
		for _, e := range m.Nodes {
			l = e.Size()
			n += 1 + l + sovMxnet(uint64(l))
		}
	}
	if len(m.ArgNodes) > 0 {
		l = 0
		for _, e := range m.ArgNodes {
			l += sovMxnet(uint64(e))
		}
		n += 1 + sovMxnet(uint64(l)) + l
	}
	if len(m.NodeRowPtr) > 0 {
		l = 0
		for _, e := range m.NodeRowPtr {
			l += sovMxnet(uint64(e))
		}
		n += 1 + sovMxnet(uint64(l)) + l
	}
	if len(m.Heads) > 0 {
		for _, e := range m.Heads {
			l = e.Size()
			n += 1 + l + sovMxnet(uint64(l))
		}
	}
	if m.Attrs != nil {
		l = m.Attrs.Size()
		n += 1 + l + sovMxnet(uint64(l))
	}
	return n
}

func (m *Graph_NodeEntry) Size() (n int) {
	var l int
	_ = l
	if m.NodeId != 0 {
		n += 1 + sovMxnet(uint64(m.NodeId))
	}
	if m.Index != 0 {
		n += 1 + sovMxnet(uint64(m.Index))
	}
	if m.Version != 0 {
		n += 1 + sovMxnet(uint64(m.Version))
	}
	return n
}

func (m *Graph_Node) Size() (n int) {
	var l int
	_ = l
	l = len(m.Op)
	if l > 0 {
		n += 1 + l + sovMxnet(uint64(l))
	}
	if len(m.Param) > 0 {
		for k, v := range m.Param {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovMxnet(uint64(len(k))) + 1 + len(v) + sovMxnet(uint64(len(v)))
			n += mapEntrySize + 1 + sovMxnet(uint64(mapEntrySize))
		}
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovMxnet(uint64(l))
	}
	if len(m.Inputs) > 0 {
		for _, e := range m.Inputs {
			l = e.Size()
			n += 1 + l + sovMxnet(uint64(l))
		}
	}
	if m.BackwardSourceId != 0 {
		n += 1 + sovMxnet(uint64(m.BackwardSourceId))
	}
	if len(m.ControlDeps) > 0 {
		l = 0
		for _, e := range m.ControlDeps {
			l += sovMxnet(uint64(e))
		}
		n += 1 + sovMxnet(uint64(l)) + l
	}
	return n
}

func (m *Graph_Attributes) Size() (n int) {
	var l int
	_ = l
	if len(m.Attrs) > 0 {
		for k, v := range m.Attrs {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovMxnet(uint64(len(k))) + 1 + len(v) + sovMxnet(uint64(len(v)))
			n += mapEntrySize + 1 + sovMxnet(uint64(mapEntrySize))
		}
	}
	return n
}

func sovMxnet(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMxnet(x uint64) (n int) {
	return sovMxnet(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Graph) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Graph{`,
		`Nodes:` + strings.Replace(fmt.Sprintf("%v", this.Nodes), "Graph_Node", "Graph_Node", 1) + `,`,
		`ArgNodes:` + fmt.Sprintf("%v", this.ArgNodes) + `,`,
		`NodeRowPtr:` + fmt.Sprintf("%v", this.NodeRowPtr) + `,`,
		`Heads:` + strings.Replace(fmt.Sprintf("%v", this.Heads), "Graph_NodeEntry", "Graph_NodeEntry", 1) + `,`,
		`Attrs:` + strings.Replace(fmt.Sprintf("%v", this.Attrs), "Graph_Attributes", "Graph_Attributes", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Graph_NodeEntry) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Graph_NodeEntry{`,
		`NodeId:` + fmt.Sprintf("%v", this.NodeId) + `,`,
		`Index:` + fmt.Sprintf("%v", this.Index) + `,`,
		`Version:` + fmt.Sprintf("%v", this.Version) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Graph_Node) String() string {
	if this == nil {
		return "nil"
	}
	keysForParam := make([]string, 0, len(this.Param))
	for k, _ := range this.Param {
		keysForParam = append(keysForParam, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForParam)
	mapStringForParam := "map[string]string{"
	for _, k := range keysForParam {
		mapStringForParam += fmt.Sprintf("%v: %v,", k, this.Param[k])
	}
	mapStringForParam += "}"
	s := strings.Join([]string{`&Graph_Node{`,
		`Op:` + fmt.Sprintf("%v", this.Op) + `,`,
		`Param:` + mapStringForParam + `,`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Inputs:` + strings.Replace(fmt.Sprintf("%v", this.Inputs), "Graph_NodeEntry", "Graph_NodeEntry", 1) + `,`,
		`BackwardSourceId:` + fmt.Sprintf("%v", this.BackwardSourceId) + `,`,
		`ControlDeps:` + fmt.Sprintf("%v", this.ControlDeps) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Graph_Attributes) String() string {
	if this == nil {
		return "nil"
	}
	keysForAttrs := make([]string, 0, len(this.Attrs))
	for k, _ := range this.Attrs {
		keysForAttrs = append(keysForAttrs, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForAttrs)
	mapStringForAttrs := "map[string]string{"
	for _, k := range keysForAttrs {
		mapStringForAttrs += fmt.Sprintf("%v: %v,", k, this.Attrs[k])
	}
	mapStringForAttrs += "}"
	s := strings.Join([]string{`&Graph_Attributes{`,
		`Attrs:` + mapStringForAttrs + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringMxnet(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Graph) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMxnet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Graph: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Graph: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nodes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMxnet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMxnet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nodes = append(m.Nodes, &Graph_Node{})
			if err := m.Nodes[len(m.Nodes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMxnet
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ArgNodes = append(m.ArgNodes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMxnet
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthMxnet
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMxnet
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ArgNodes = append(m.ArgNodes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ArgNodes", wireType)
			}
		case 3:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMxnet
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.NodeRowPtr = append(m.NodeRowPtr, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMxnet
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthMxnet
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMxnet
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.NodeRowPtr = append(m.NodeRowPtr, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeRowPtr", wireType)
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Heads", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMxnet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMxnet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Heads = append(m.Heads, &Graph_NodeEntry{})
			if err := m.Heads[len(m.Heads)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attrs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMxnet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMxnet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Attrs == nil {
				m.Attrs = &Graph_Attributes{}
			}
			if err := m.Attrs.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMxnet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMxnet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Graph_NodeEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMxnet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			m.NodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMxnet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMxnet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMxnet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMxnet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMxnet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Graph_Node) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMxnet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Node: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Node: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Op", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMxnet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMxnet
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Op = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Param", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMxnet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMxnet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var keykey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMxnet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				keykey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var stringLenmapkey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMxnet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLenmapkey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLenmapkey := int(stringLenmapkey)
			if intStringLenmapkey < 0 {
				return ErrInvalidLengthMxnet
			}
			postStringIndexmapkey := iNdEx + intStringLenmapkey
			if postStringIndexmapkey > l {
				return io.ErrUnexpectedEOF
			}
			mapkey := string(dAtA[iNdEx:postStringIndexmapkey])
			iNdEx = postStringIndexmapkey
			if m.Param == nil {
				m.Param = make(map[string]string)
			}
			if iNdEx < postIndex {
				var valuekey uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMxnet
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					valuekey |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				var stringLenmapvalue uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMxnet
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLenmapvalue |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLenmapvalue := int(stringLenmapvalue)
				if intStringLenmapvalue < 0 {
					return ErrInvalidLengthMxnet
				}
				postStringIndexmapvalue := iNdEx + intStringLenmapvalue
				if postStringIndexmapvalue > l {
					return io.ErrUnexpectedEOF
				}
				mapvalue := string(dAtA[iNdEx:postStringIndexmapvalue])
				iNdEx = postStringIndexmapvalue
				m.Param[mapkey] = mapvalue
			} else {
				var mapvalue string
				m.Param[mapkey] = mapvalue
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMxnet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMxnet
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inputs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMxnet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMxnet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inputs = append(m.Inputs, &Graph_NodeEntry{})
			if err := m.Inputs[len(m.Inputs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BackwardSourceId", wireType)
			}
			m.BackwardSourceId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMxnet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BackwardSourceId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMxnet
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ControlDeps = append(m.ControlDeps, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMxnet
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthMxnet
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMxnet
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ControlDeps = append(m.ControlDeps, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ControlDeps", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMxnet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMxnet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Graph_Attributes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMxnet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Attributes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Attributes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attrs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMxnet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMxnet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var keykey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMxnet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				keykey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var stringLenmapkey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMxnet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLenmapkey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLenmapkey := int(stringLenmapkey)
			if intStringLenmapkey < 0 {
				return ErrInvalidLengthMxnet
			}
			postStringIndexmapkey := iNdEx + intStringLenmapkey
			if postStringIndexmapkey > l {
				return io.ErrUnexpectedEOF
			}
			mapkey := string(dAtA[iNdEx:postStringIndexmapkey])
			iNdEx = postStringIndexmapkey
			if m.Attrs == nil {
				m.Attrs = make(map[string]string)
			}
			if iNdEx < postIndex {
				var valuekey uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMxnet
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					valuekey |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				var stringLenmapvalue uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMxnet
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLenmapvalue |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLenmapvalue := int(stringLenmapvalue)
				if intStringLenmapvalue < 0 {
					return ErrInvalidLengthMxnet
				}
				postStringIndexmapvalue := iNdEx + intStringLenmapvalue
				if postStringIndexmapvalue > l {
					return io.ErrUnexpectedEOF
				}
				mapvalue := string(dAtA[iNdEx:postStringIndexmapvalue])
				iNdEx = postStringIndexmapvalue
				m.Attrs[mapkey] = mapvalue
			} else {
				var mapvalue string
				m.Attrs[mapkey] = mapvalue
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMxnet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMxnet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMxnet(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMxnet
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMxnet
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMxnet
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMxnet
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMxnet
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMxnet(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMxnet = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMxnet   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("mxnet.proto", fileDescriptorMxnet) }

var fileDescriptorMxnet = []byte{
	// 739 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x41, 0x6f, 0xd3, 0x48,
	0x14, 0xee, 0x24, 0x75, 0xba, 0x99, 0x44, 0xda, 0xee, 0x74, 0xb7, 0xeb, 0x8d, 0x76, 0xed, 0xc8,
	0x2b, 0xed, 0xe6, 0x40, 0x5d, 0x11, 0x84, 0x1a, 0x15, 0x71, 0x20, 0x05, 0x55, 0x05, 0xa9, 0xaa,
	0xcc, 0x0d, 0x09, 0xa2, 0x49, 0x3c, 0x4d, 0xa3, 0xc6, 0x1e, 0x6b, 0x3c, 0x69, 0x1a, 0x09, 0xa4,
	0x4a, 0x5c, 0x7a, 0xe4, 0x67, 0xf0, 0x13, 0x38, 0x72, 0xe4, 0x08, 0x37, 0x4e, 0x56, 0x13, 0x4e,
	0xe4, 0x84, 0x7a, 0x42, 0xe2, 0x82, 0xf2, 0x26, 0x6d, 0xe2, 0xd4, 0x42, 0x04, 0x6e, 0x33, 0xef,
	0x9b, 0xf9, 0xbe, 0xf7, 0xbe, 0x79, 0x7e, 0xc6, 0x39, 0xef, 0xd8, 0x67, 0xd2, 0x0e, 0x04, 0x97,
	0x9c, 0xfc, 0xd7, 0xa0, 0xc2, 0x6b, 0xdb, 0x5c, 0x34, 0x6d, 0xb7, 0xbd, 0x2f, 0xa8, 0xc7, 0xba,
	0x5c, 0x1c, 0xda, 0x97, 0xab, 0xd0, 0x86, 0xd3, 0x85, 0xb5, 0x66, 0x4b, 0x1e, 0x74, 0xea, 0x76,
	0x83, 0x7b, 0xeb, 0x4d, 0xde, 0xe4, 0xeb, 0x70, 0xbd, 0xde, 0xd9, 0x87, 0x1d, 0x6c, 0x60, 0xa5,
	0x68, 0xad, 0x2f, 0x79, 0xac, 0x6d, 0x0b, 0x1a, 0x1c, 0x90, 0x2e, 0xd6, 0x7c, 0xee, 0xb2, 0x50,
	0x47, 0xc5, 0x74, 0x29, 0x57, 0x2e, 0xdb, 0xdf, 0x27, 0x68, 0xc3, 0x6d, 0x7b, 0x97, 0xbb, 0xac,
	0xba, 0x36, 0x8c, 0xcc, 0x5f, 0x81, 0xe4, 0x1a, 0xf7, 0x5a, 0x92, 0x79, 0x81, 0xec, 0x9d, 0x47,
	0xe6, 0x6a, 0x8f, 0x7a, 0xed, 0x4d, 0x6b, 0x06, 0xb0, 0x1c, 0xa5, 0x47, 0x1c, 0x9c, 0xa5, 0xa2,
	0x59, 0x53, 0xe2, 0xa9, 0x62, 0xba, 0x94, 0xae, 0xde, 0x1c, 0x46, 0xe6, 0xca, 0x65, 0x30, 0x46,
	0x56, 0x50, 0x64, 0x09, 0xa0, 0xe5, 0xfc, 0x42, 0x45, 0x73, 0x17, 0x38, 0x1f, 0xe3, 0xfc, 0x08,
	0xad, 0x09, 0xde, 0xad, 0x05, 0x52, 0xe8, 0x69, 0xa0, 0xbd, 0x35, 0x8c, 0xcc, 0xd5, 0xe9, 0x78,
	0x8c, 0xf9, 0x9f, 0x49, 0x9a, 0x57, 0x71, 0xcb, 0xc1, 0x23, 0xc0, 0xe1, 0xdd, 0x3d, 0x29, 0xc8,
	0x53, 0xac, 0x1d, 0x30, 0xea, 0x86, 0xfa, 0x22, 0x78, 0xb5, 0x31, 0xbf, 0x57, 0xf7, 0x7c, 0x29,
	0x7a, 0xca, 0x30, 0x60, 0x4a, 0x32, 0x6c, 0x06, 0xb0, 0x1c, 0x25, 0x4a, 0x9e, 0x61, 0x8d, 0x4a,
	0x29, 0x42, 0x5d, 0x2b, 0xa2, 0x52, 0xae, 0x5c, 0x99, 0x4f, 0xfd, 0x8e, 0x94, 0xa2, 0x55, 0xef,
	0x48, 0x16, 0x2a, 0x79, 0xa0, 0x4a, 0x92, 0x9f, 0x01, 0x2c, 0x47, 0xa9, 0x16, 0x3e, 0x22, 0x9c,
	0xbd, 0x2c, 0x81, 0xdc, 0xc7, 0x4b, 0xe0, 0x58, 0xcb, 0xd5, 0x51, 0x11, 0x95, 0xd2, 0xd5, 0xeb,
	0xc3, 0xc8, 0xfc, 0x6d, 0x1c, 0x8a, 0xd1, 0xea, 0x53, 0xfe, 0x4e, 0x43, 0x96, 0x93, 0x19, 0xc5,
	0x76, 0x5c, 0xb2, 0x85, 0xb5, 0x96, 0xef, 0xb2, 0x63, 0x3d, 0x05, 0x4c, 0x90, 0x1e, 0x04, 0x92,
	0xd2, 0x6b, 0xf9, 0x41, 0x47, 0xc6, 0xd2, 0x83, 0xa3, 0xe4, 0x01, 0x5e, 0x3a, 0x62, 0x22, 0x6c,
	0x71, 0x5f, 0x4f, 0x4f, 0x12, 0x1a, 0x87, 0x92, 0x12, 0xba, 0x02, 0x59, 0xce, 0x05, 0x43, 0xe1,
	0x54, 0xc3, 0x8b, 0xa3, 0x5a, 0xc9, 0x06, 0x4e, 0xf1, 0x00, 0x2a, 0xcc, 0x56, 0xff, 0x1f, 0x46,
	0x66, 0x9e, 0x07, 0x31, 0xae, 0x15, 0xc5, 0x35, 0x1d, 0xb5, 0x9c, 0x14, 0x0f, 0xc8, 0x73, 0x84,
	0xb5, 0x80, 0x0a, 0xea, 0x41, 0x6b, 0xe7, 0xca, 0xb7, 0xe7, 0xef, 0x15, 0x7b, 0x6f, 0x74, 0x5f,
	0x75, 0x8c, 0x3d, 0xf2, 0x04, 0xf8, 0x62, 0xf2, 0x7f, 0x2a, 0x79, 0x00, 0xe2, 0x6f, 0x06, 0x21,
	0xb2, 0x86, 0x17, 0x7d, 0xea, 0x31, 0x70, 0x24, 0x5b, 0xfd, 0xeb, 0x3c, 0x32, 0xff, 0x18, 0xbf,
	0x06, 0xf5, 0xd8, 0xf4, 0x79, 0x38, 0x46, 0x4e, 0x10, 0xce, 0x80, 0xbf, 0x3f, 0xdd, 0xe1, 0xeb,
	0xc3, 0xc8, 0x5c, 0x56, 0x54, 0x49, 0x09, 0xcf, 0x22, 0x96, 0x33, 0xd6, 0x25, 0x1d, 0x4c, 0xea,
	0xb4, 0x71, 0xd8, 0xa5, 0xc2, 0xad, 0x85, 0xbc, 0x23, 0x1a, 0xd0, 0x62, 0x1a, 0xbc, 0xe8, 0xf6,
	0x30, 0x32, 0xff, 0xbe, 0x8a, 0xc6, 0x04, 0xfe, 0x55, 0x02, 0xdf, 0x3a, 0x65, 0x39, 0xcb, 0x17,
	0xf0, 0x43, 0x40, 0x77, 0x5c, 0xf2, 0x04, 0xe7, 0x1b, 0xdc, 0x97, 0x82, 0xb7, 0x6b, 0x2e, 0x0b,
	0x42, 0x3d, 0x33, 0x19, 0x1c, 0xd3, 0xf1, 0xa4, 0xc1, 0x91, 0x8c, 0x5b, 0x4e, 0x6e, 0x0c, 0xdc,
	0x65, 0x41, 0x58, 0xa8, 0x60, 0x3c, 0x79, 0x4d, 0xb2, 0x8c, 0xd3, 0x87, 0xac, 0xa7, 0xda, 0xca,
	0x19, 0x2d, 0xc9, 0xef, 0x58, 0x3b, 0xa2, 0xed, 0x0e, 0x83, 0x4f, 0x20, 0xeb, 0xa8, 0xcd, 0x66,
	0xaa, 0x82, 0x0a, 0xef, 0x10, 0xc6, 0x93, 0x6f, 0x97, 0x9c, 0xa2, 0x8b, 0x29, 0xa0, 0xe6, 0xf5,
	0xd6, 0x8f, 0x4e, 0x01, 0x58, 0x86, 0x53, 0xf3, 0x68, 0xee, 0x81, 0x50, 0x51, 0x89, 0x85, 0x73,
	0xd7, 0x54, 0xdd, 0x78, 0xdf, 0x37, 0x16, 0xce, 0xfa, 0x06, 0xfa, 0xd4, 0x37, 0xd0, 0xe7, 0xbe,
	0x81, 0x4e, 0x06, 0x06, 0x7a, 0x39, 0x30, 0xd0, 0xab, 0x81, 0x81, 0x5e, 0x0f, 0x0c, 0xf4, 0x66,
	0x60, 0xa0, 0xb7, 0x03, 0x03, 0x9d, 0x0d, 0x0c, 0xf4, 0xe2, 0x83, 0xb1, 0xf0, 0x48, 0x83, 0x22,
	0xea, 0x19, 0xf8, 0x7b, 0xdd, 0xf8, 0x1a, 0x00, 0x00, 0xff, 0xff, 0x77, 0x35, 0x28, 0x26, 0x23,
	0x07, 0x00, 0x00,
}
